### ISSUE TITLE
能不能先看一下结果

### ISSUE THREAD

**Issue by zuowanbushiwo** [caoruitju/RUI_SE#1]
对这个项目非常好奇，不知道能不能把结果的图片贴出来看看，想看一下对比提升了多少，谢谢！

**Comment by wangtianrui** [comment]
仓库还在维护中，具体方法细节和实验结果可以查阅预发表论文：https://arxiv.org/abs/2312.11201

**Comment by caoruitju** [comment]
具体实验结果及描述请参照预发表论文

**Comment by zuowanbushiwo** [comment]
谢谢，看了文章，效果提升很多。祝您的文章早日发表
