### ISSUE TITLE
提供的npy文件和HAPNet计算的comb-pitch conversation matrix不一致

### ISSUE THREAD

**Issue by SherryYu33** [caoruitju/RUI_SE#2]
您好

我按照Harmonic Attention for Monaural Speech Enhancement中提供的伪代码计算了comb-pitch conversation matrix，但是和您提供的npy文件不一样，请问是采用了新的计算方法吗？

谢谢！

**Comment by wangtianrui** [comment]
后来实验里发现在矩阵的0~pitch区域加一个谷建模可以有效减少预测pitch时倍频和半频的问题
